[package]
name = "hor-registry"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
mediator-config = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true, features = ["derive"] }
